### ISSUE TITLE
build 命令执行报错

### ISSUE THREAD

**Issue by binaryYuki** [mtianyan/django-react-tyadmin#54]
#### Current Behavior
When running `yarn build`, the build process fails with the following error:

```node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/Users/tingzhanghuang/Documents/self-effort/basic_service_platform/tyadmin/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/tingzhanghuang/Documents/self-effort/basic_service_platform/tyadmin/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/tingzhanghuang/Documents/self-effort/basic_service_platform/tyadmin/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/tingzhanghuang/Documents/self-effort/basic_service_platform/tyadmin/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/tingzhanghuang/Documents/self-effort/basic_service_platform/tyadmin/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/tingzhanghuang/Documents/self-effort/basic_service_platform/tyadmin/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/tingzhanghuang/Documents/self-effort/basic_service_platform/tyadmin/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/tingzhanghuang/Documents/self-effort/basic_service_platform/tyadmin/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

#### Expected Behavior
The build process should complete successfully without any errors.

#### Steps to Reproduce
1. Run `yarn build` command.

#### Environment
- Operating System: MacOS
- Node Version: node v16.20.2
- Yarn Version: v1.22.19

**Comment by binaryYuki** [comment]
补充原因：node版本太高 nvm降级就行
